### ISSUE TITLE
CI Failure: Google Maps API Key Environment Variable Not Configured and DB Connection Refused

### ISSUE THREAD

**Issue by portalman32** [Alamo-Tech-Collective/Taco-Price-Index#21]
What happened: The CI pipeline failed during the test stage, I also noticed that the connection is refused for the database in the logs.

Expected behavior: The CI pipeline should complete successfully, with the Google Maps API key being loaded correctly and the database connection should have succeeded.

Proposed solution (By GitHub Copilot): 

1. **Missing Environment Variable:**
   - The logs show: WARNING: GOOGLE_MAPS_API_KEY is not set in the environment variables.
   - Solution: Add the GOOGLE_MAPS_API_KEY to your GitHub Actions secrets and inject it in your workflow. Example:
     ```
     - name: Run tests
       env:
         RAILS_ENV: test
         GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
       run: bin/rails db:test:prepare test test:system
     ```
     Also, make sure to add the secret in your repository settings: Settings → Secrets and variables → Actions → New repository secret.

2. **Database Connection Refused (PostgreSQL):**
   - The logs indicate: connection to server at "::1", port 5432 failed: Connection refused
   - Your workflow does not start a PostgreSQL service for the test job. Add the PostgreSQL service under the test job:
     ```
     test:
       runs-on: ubuntu-latest
       services:
         postgres:
           image: postgres:13
           ports:
             - 5432:5432
           env:
             POSTGRES_USER: postgres
             POSTGRES_PASSWORD: postgres
             POSTGRES_DB: test
           options: >-
             --health-cmd="pg_isready"
             --health-interval=10s
             --health-timeout=5s
             --health-retries=5
       steps:
         # ... your steps ...
         - name: Run tests
           env:
             RAILS_ENV: test
             PGUSER: postgres
             PGPASSWORD: postgres
             PGHOST: localhost
             PGDATABASE: test
             GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
           run: bin/rails db:test:prepare test test:system
     ```

Apply these fixes in your workflow file (.github/workflows/ci.yml) under the test job. This will resolve the environment variable and database connection issues causing the failure. 

Links for reference:
- Workflow file: [.github/workflows/ci.yml](https://github.com/Alamo-Tech-Collective/Taco-Price-Index/blob/d7b77f94eaf83c0eed0d40e638df62535312e2ff/.github/workflows/ci.yml)
